export type Guide = {
  name: string;
  role: string;
  languages: string[];
  rating: number;
  reviews: number;
  bio: string;
  initials: string;
};

export type Tour = {
  slug: string;
  title: string;
  meta: string;
  img: string;
  price?: number;
  days: number;
  bestTime?: string;
  style: string;
  region: string;
  collections?: ("sublime" | "halal")[];
  tags?: string[];
  summary: string;
  included: string[];
  excluded: string[];
  whatToExpect: string[];
  activities: string[];
  itinerary: { title: string; desc: string }[];
  faqs: { q: string; a: string }[];
  rating: { score: number; count: number };
  gallery: string[];
  guide?: Guide;
};

/** Live catalogue, fetched from the Tanova Vendor API (GET /services/tours) on 2026-09-29.
 *  Fields the API had no data for (itinerary, FAQs, guide, rating, bestTime for most tours)
 *  are left empty/omitted rather than invented — see conversation record for details. */
export const TOURS: Tour[] = [
  {
    slug: "8-day-northern-circuit-group-trek",
    title: "8-Day Northern Circuit Group Trek",
    meta: "8 Days · Tanzania",
    img: "/img/real-api/tours/8-day-northern-circuit-group-trek/1.webp",
    price: 2900,
    days: 8, style: "Safari & Wildlife", region: "Serengeti National Park",
    summary: "A fixed-date, small-group 8-day circuit across northern Tanzania's parks — travelers join a scheduled departure alongside other guests instead of booking a private itinerary. Combines game drives across the northern-circuit parks (Tarangire, Lake Manyara, Ngorongoro Crater and the Serengeti) with lodge/camp accommodation. Group departure dates (from the operator's published schedule; dates already past are kept here for reference — only upcoming dates are bookable): 11 January 2026 — $290",
    included: [],
    excluded: [], whatToExpect: [], activities: [], itinerary: [], faqs: [],
    rating: { score: 0, count: 0 },
    gallery: ["/img/real-api/tours/8-day-northern-circuit-group-trek/1.webp", "/img/real-api/tours/8-day-northern-circuit-group-trek/2.jpg", "/img/real-api/tours/8-day-northern-circuit-group-trek/3.webp", "/img/real-api/tours/8-day-northern-circuit-group-trek/4.webp", "/img/real-api/tours/8-day-northern-circuit-group-trek/5.jpg", "/img/real-api/tours/8-day-northern-circuit-group-trek/6.webp"],
  },
  {
    slug: "8-day-kilimanjaro-group-trek-via-lemosho-route",
    title: "8-Day Kilimanjaro Group Trek via Lemosho Route",
    meta: "8 Days · Tanzania",
    img: "/img/real-api/tours/8-day-kilimanjaro-group-trek-via-lemosho-route/1.webp",
    price: 2670,
    days: 8, style: "Adrenaline & Adventure", region: "Mount Kilimanjaro",
    summary: "A fixed-date, small-group ascent of Mount Kilimanjaro via the Lemosho route, run over 8 days on set joining dates rather than a private booking — travelers join a scheduled group instead of booking the whole trip privately. Lemosho starts at Londorossi Gate and crosses rainforest, alpine desert and near-arctic terrain on the way to Uhuru Peak — the extra days build in better acclimatization for a higher summit success rate. Group departure dates (from the operator's published schedule; date",
    included: [],
    excluded: [], whatToExpect: [], activities: [], itinerary: [], faqs: [],
    rating: { score: 0, count: 0 },
    gallery: ["/img/real-api/tours/8-day-kilimanjaro-group-trek-via-lemosho-route/1.webp", "/img/real-api/tours/8-day-kilimanjaro-group-trek-via-lemosho-route/2.jpg", "/img/real-api/tours/8-day-kilimanjaro-group-trek-via-lemosho-route/3.webp", "/img/real-api/tours/8-day-kilimanjaro-group-trek-via-lemosho-route/4.webp", "/img/real-api/tours/8-day-kilimanjaro-group-trek-via-lemosho-route/5.jpg", "/img/real-api/tours/8-day-kilimanjaro-group-trek-via-lemosho-route/6.webp"],
  },
  {
    slug: "7-day-kilimanjaro-group-trek-via-lemosho-route",
    title: "7-Day Kilimanjaro Group Trek via Lemosho Route",
    meta: "7 Days · Tanzania",
    img: "/img/real-api/tours/7-day-kilimanjaro-group-trek-via-lemosho-route/1.webp",
    price: 2670,
    days: 7, style: "Adrenaline & Adventure", region: "Mount Kilimanjaro",
    summary: "A fixed-date, small-group ascent of Mount Kilimanjaro via the Lemosho route, run over 7 days on set joining dates rather than a private booking — travelers join a scheduled group instead of booking the whole trip privately. Lemosho starts at Londorossi Gate and crosses rainforest, alpine desert and near-arctic terrain on the way to Uhuru Peak — the extra days build in better acclimatization for a higher summit success rate. Group departure dates (from the operator's published schedule; date",
    included: [],
    excluded: [], whatToExpect: [], activities: [], itinerary: [], faqs: [],
    rating: { score: 0, count: 0 },
    gallery: ["/img/real-api/tours/7-day-kilimanjaro-group-trek-via-lemosho-route/1.webp", "/img/real-api/tours/7-day-kilimanjaro-group-trek-via-lemosho-route/2.jpg", "/img/real-api/tours/7-day-kilimanjaro-group-trek-via-lemosho-route/3.webp", "/img/real-api/tours/7-day-kilimanjaro-group-trek-via-lemosho-route/4.webp", "/img/real-api/tours/7-day-kilimanjaro-group-trek-via-lemosho-route/5.jpg", "/img/real-api/tours/7-day-kilimanjaro-group-trek-via-lemosho-route/6.webp"],
  },
  {
    slug: "7-day-kilimanjaro-group-trek-via-machame-route",
    title: "7-Day Kilimanjaro Group Trek via Machame Route",
    meta: "7 Days · Tanzania",
    img: "/img/real-api/tours/7-day-kilimanjaro-group-trek-via-machame-route/1.webp",
    price: 2470,
    days: 7, style: "Adrenaline & Adventure", region: "Mount Kilimanjaro",
    summary: "A fixed-date, small-group ascent of Mount Kilimanjaro via the Machame route, run over 7 days on set joining dates rather than a private booking — travelers join a scheduled group instead of booking the whole trip privately. Known as the 'Whiskey' route, Machame is one of Kilimanjaro's more scenic paths, crossing rainforest, moorland and alpine terrain before a midnight summit push to Uhuru Peak. Group departure dates (from the operator's published schedule; dates already past are kept here",
    included: [],
    excluded: [], whatToExpect: [], activities: [], itinerary: [], faqs: [],
    rating: { score: 0, count: 0 },
    gallery: ["/img/real-api/tours/7-day-kilimanjaro-group-trek-via-machame-route/1.webp", "/img/real-api/tours/7-day-kilimanjaro-group-trek-via-machame-route/2.jpg", "/img/real-api/tours/7-day-kilimanjaro-group-trek-via-machame-route/3.webp", "/img/real-api/tours/7-day-kilimanjaro-group-trek-via-machame-route/4.webp", "/img/real-api/tours/7-day-kilimanjaro-group-trek-via-machame-route/5.jpg", "/img/real-api/tours/7-day-kilimanjaro-group-trek-via-machame-route/6.webp"],
  },
  {
    slug: "6-day-kilimanjaro-group-trek-via-marangu-route",
    title: "6-Day Kilimanjaro Group Trek via Marangu Route",
    meta: "6 Days · Tanzania",
    img: "/img/real-api/tours/6-day-kilimanjaro-group-trek-via-marangu-route/1.jpg",
    price: 2160,
    days: 6, style: "Adrenaline & Adventure", region: "Mount Kilimanjaro",
    summary: "A fixed-date, small-group ascent of Mount Kilimanjaro via the Marangu route, run over 6 days on set joining dates rather than a private booking — travelers join a scheduled group instead of booking the whole trip privately. Marangu is Kilimanjaro's only hut-based route (sleeping huts rather than tents), climbing through rainforest, heathland and alpine terrain with a rest day at Horombo for acclimatization before the summit push. Group departure dates (from the operator's published schedule",
    included: [],
    excluded: [], whatToExpect: [], activities: [], itinerary: [], faqs: [],
    rating: { score: 0, count: 0 },
    gallery: ["/img/real-api/tours/6-day-kilimanjaro-group-trek-via-marangu-route/1.jpg", "/img/real-api/tours/6-day-kilimanjaro-group-trek-via-marangu-route/2.jpg", "/img/real-api/tours/6-day-kilimanjaro-group-trek-via-marangu-route/3.webp", "/img/real-api/tours/6-day-kilimanjaro-group-trek-via-marangu-route/4.jpg", "/img/real-api/tours/6-day-kilimanjaro-group-trek-via-marangu-route/5.jpg", "/img/real-api/tours/6-day-kilimanjaro-group-trek-via-marangu-route/6.webp"],
  },
  {
    slug: "6-day-kilimanjaro-group-trek-via-machame-route",
    title: "6-Day Kilimanjaro Group Trek via Machame Route",
    meta: "6 Days · Tanzania",
    img: "/img/real-api/tours/6-day-kilimanjaro-group-trek-via-machame-route/1.webp",
    price: 2470,
    days: 6, style: "Adrenaline & Adventure", region: "Mount Kilimanjaro",
    summary: "A fixed-date, small-group ascent of Mount Kilimanjaro via the Machame route, run over 6 days on set joining dates rather than a private booking — travelers join a scheduled group instead of booking the whole trip privately. Known as the 'Whiskey' route, Machame is one of Kilimanjaro's more scenic paths, crossing rainforest, moorland and alpine terrain before a midnight summit push to Uhuru Peak. Group departure dates (from the operator's published schedule; dates already past are kept here",
    included: [],
    excluded: [], whatToExpect: [], activities: [], itinerary: [], faqs: [],
    rating: { score: 0, count: 0 },
    gallery: ["/img/real-api/tours/6-day-kilimanjaro-group-trek-via-machame-route/1.webp", "/img/real-api/tours/6-day-kilimanjaro-group-trek-via-machame-route/2.jpg", "/img/real-api/tours/6-day-kilimanjaro-group-trek-via-machame-route/3.webp"],
  },
  {
    slug: "luxury-golf-serengeti-migration-safari",
    title: "Luxury Golf & Serengeti Migration Safari",
    meta: "9 Days · Tanzania",
    img: "/img/real-api/tours/luxury-golf-serengeti-migration-safari/1.webp",
    price: 4596,
    days: 9, style: "Safari & Wildlife", region: "Serengeti National Park",
    collections: ["sublime"],
    summary: "A niche itinerary pairing two rounds of golf at the Kilimanjaro Golf Estate with a Great Migration safari through the Serengeti, Ngorongoro Crater and Tarangire. A scenic flight connects Arusha to the Serengeti, and accommodation ranges from a luxury lodge to tented safari camps. Best timed to the July-September migration peak, with all game drives, park fees and transfers included.",
    included: ["Two 18-hole golf rounds with caddie & cart", "scenic flight Arusha-Serengeti", "full board safari accommodation", "all game drives & park fees", "unlimited drinking water"],
    excluded: [], whatToExpect: [], activities: [], itinerary: [], faqs: [],
    rating: { score: 0, count: 0 },
    gallery: ["/img/real-api/tours/luxury-golf-serengeti-migration-safari/1.webp", "/img/real-api/tours/luxury-golf-serengeti-migration-safari/2.webp"],
  },
  {
    slug: "moshi-tuk-tuk-tour-3-day-cultural-and-nature-adventure",
    title: "Moshi Tuk Tuk Tour: 3-Day Cultural and Nature Adventure",
    meta: "3 Days · Tanzania",
    img: "/img/real-api/tours/moshi-tuk-tuk-tour-3-day-cultural-and-nature-adventure/1.webp",
    days: 3, style: "Sightseeing & Tours", region: "Materuni",
    collections: ["halal"],
    summary: "A tuk-tuk-based city and countryside tour around Moshi, Tanzania's coffee-growing gateway town to Kilimanjaro. It mixes a town tour of markets, churches and colonial-era sites with a hike and swim at Materuni Waterfall and a hands-on coffee plantation visit. Private and guide-led, it runs best in the June-October dry season, with Kilimanjaro views weather permitting.",
    included: ["Moshi town tour", "Materuni Waterfall hike & swim", "coffee plantation visit", "airport transfers", "all meals", "experienced local guide"],
    excluded: [], whatToExpect: [], activities: [], itinerary: [], faqs: [],
    rating: { score: 0, count: 0 },
    gallery: ["/img/real-api/tours/moshi-tuk-tuk-tour-3-day-cultural-and-nature-adventure/1.webp"],
  },
  {
    slug: "tanzanian-trio-safari-tarangire-manyara-ngorongoro-expedition",
    title: "Tanzanian Trio Safari - Tarangire, Manyara, Ngorongoro Expedition",
    meta: "4 Days · Tanzania",
    img: "/img/real-api/tours/tanzanian-trio-safari-tarangire-manyara-ngorongoro-expedition/1.webp",
    price: 1274,
    days: 4, style: "Safari & Wildlife", region: "Tarangire National Park",
    summary: "A compact four-day northern circuit covering Tarangire's elephant herds and baobabs, Lake Manyara's tree-climbing lions and flamingos, and the Ngorongoro Crater's self-contained Big Five ecosystem. It's a private, customizable trip with lodge/camp stays, full board and an English-speaking guide. International flights, insurance and tips are not included.",
    included: ["Big Five game drives across three parks", "tree-climbing lions at Manyara", "Ngorongoro Crater visit", "Maasai cultural engagement", "lodge/camp accommodation", "picnic meals"],
    excluded: [], whatToExpect: [], activities: [], itinerary: [], faqs: [],
    rating: { score: 0, count: 0 },
    gallery: ["/img/real-api/tours/tanzanian-trio-safari-tarangire-manyara-ngorongoro-expedition/1.webp", "/img/real-api/tours/tanzanian-trio-safari-tarangire-manyara-ngorongoro-expedition/2.jpg", "/img/real-api/tours/tanzanian-trio-safari-tarangire-manyara-ngorongoro-expedition/3.jpg", "/img/real-api/tours/tanzanian-trio-safari-tarangire-manyara-ngorongoro-expedition/4.jpg"],
  },
  {
    slug: "southern-tanzania-discovery",
    title: "Southern Tanzania Discovery",
    meta: "9 Days · Tanzania",
    img: "/img/real-api/tours/southern-tanzania-discovery/1.jpg",
    price: 4980,
    days: 9, style: "Safari & Wildlife", region: "Tanzania",
    collections: ["halal"],
    summary: "A nine-day circuit through Tanzania's less-visited southern parks - Ruaha, Mikumi and Nyerere - combining classic game drives with a boat safari on the Rufiji River. Domestic flights connect the parks, and travelers stay in luxury lodges and tented camps on full board, departing from and returning to Dar es Salaam. Best from June through October, with an optional night game drive.",
    included: ["Game drives across three parks", "Rufiji River boat safari", "domestic flights included", "full board lodges/camps", "birdwatching", "optional night game drive"],
    excluded: [], whatToExpect: [], activities: [], itinerary: [], faqs: [],
    rating: { score: 0, count: 0 },
    gallery: ["/img/real-api/tours/southern-tanzania-discovery/1.jpg", "/img/real-api/tours/southern-tanzania-discovery/2.jpg", "/img/real-api/tours/southern-tanzania-discovery/3.jpg"],
  },
  {
    slug: "lake-dreams",
    title: "Lake Dreams",
    meta: "1 Day · Tanzania",
    img: "/img/real-api/tours/lake-dreams/1.webp",
    days: 1, style: "Safari & Wildlife", region: "Arusha",
    summary: "A single-day outing in Arusha National Park that opens with an early canoe paddle on the Momella Lakes, followed by a guided nature walk, a picnic lunch, and an afternoon game drive with views of Mount Meru. Wildlife on show includes buffalo, giraffe, waterbuck and colobus and blue monkeys. Suitable for all ages, with optional add-ons like a waterfall or Mount Meru day hike.",
    included: ["Guided canoe excursion", "ranger-led nature walk", "picnic lunch", "afternoon game drive", "park & conservation fees", "optional waterfall or Meru day hike"],
    excluded: [], whatToExpect: [], activities: [], itinerary: [], faqs: [],
    rating: { score: 0, count: 0 },
    gallery: ["/img/real-api/tours/lake-dreams/1.webp", "/img/real-api/tours/lake-dreams/2.webp"],
  },
  {
    slug: "manyara-explorers-delight-3-day-wildlife-and-culture-safari",
    title: "Manyara Explorer's Delight: 3-Day Wildlife and Culture Safari",
    meta: "3 Days · Tanzania",
    img: "/img/real-api/tours/manyara-explorers-delight-3-day-wildlife-and-culture-safari/1.webp",
    days: 3, style: "Safari & Wildlife", region: "Lake Manyara National Park",
    collections: ["halal"],
    summary: "A short Arusha-based safari to Lake Manyara National Park featuring a treetop canopy walk, sunrise and morning game drives for Big Five sightings, and a canoe safari on the lake itself. A Maasai village visit with traditional dance rounds out the cultural side. It's a private, tailorable itinerary with full board lodging and 4x4 transport, peaking June-October and January-February.",
    included: ["Treetop Canopy Walk", "sunrise & morning game drives", "canoeing safari on Lake Manyara", "Maasai village visit", "full board lodge stay", "4x4 transport"],
    excluded: [], whatToExpect: [], activities: [], itinerary: [], faqs: [],
    rating: { score: 0, count: 0 },
    gallery: ["/img/real-api/tours/manyara-explorers-delight-3-day-wildlife-and-culture-safari/1.webp"],
  },
  {
    slug: "the-island-bliss",
    title: "The Island Bliss",
    meta: "5 Days · Tanzania",
    img: "/img/real-api/tours/the-island-bliss/1.jpg",
    days: 5, style: "Sightseeing & Tours", region: "Tanzania",
    collections: ["halal"],
    summary: "An Indian Ocean island retreat on Mafia Island mixing beach relaxation with scuba diving on coral reefs, a traditional dhow sail with snorkeling, and a Swahili cooking class. Historical ruins are also on the itinerary, along with spa treatments and seafood dining at a resort with full board. It suits divers, history buffs, food lovers and couples, best visited June to September.",
    included: ["Scuba diving excursions", "dhow sailing & snorkeling", "Swahili cooking class", "historical ruins tour", "resort full board", "spa treatments"],
    excluded: [], whatToExpect: [], activities: [], itinerary: [], faqs: [],
    rating: { score: 0, count: 0 },
    gallery: ["/img/real-api/tours/the-island-bliss/1.jpg"],
  },
  {
    slug: "turquoise-temptation-zanzibar-tour",
    title: "Turquoise Temptation - Zanzibar Tour",
    meta: "5 Days · Tanzania",
    img: "/img/real-api/tours/turquoise-temptation-zanzibar-tour/1.webp",
    days: 5, style: "Sightseeing & Tours", region: "Zanzibar",
    summary: "A beach-and-culture Zanzibar itinerary covering Stone Town's UNESCO-listed old quarter, a spice plantation tour, wildlife viewing for red colobus monkeys in Jozani Forest, and a day trip out to the Nakupenda Sandbank. Optional water activities include snorkeling, diving and dolphin swimming. Accommodation, meals, guides, transport and park fees are included; flights and insurance are not.",
    included: ["Stone Town tour", "spice plantation visit", "Jozani Forest colobus monkeys", "Nakupenda Sandbank trip", "optional snorkeling/diving/dolphin swim"],
    excluded: [], whatToExpect: [], activities: [], itinerary: [], faqs: [],
    rating: { score: 0, count: 0 },
    gallery: ["/img/real-api/tours/turquoise-temptation-zanzibar-tour/1.webp"],
  },
  {
    slug: "migration-wilderness-wanderlust",
    title: "Migration Wilderness Wanderlust",
    meta: "8 Days · Tanzania",
    img: "/img/real-api/tours/migration-wilderness-wanderlust/1.webp",
    days: 8, style: "Safari & Wildlife", region: "Serengeti National Park",
    collections: ["sublime"],
    summary: "An eight-day safari across four of northern Tanzania's premier parks, timed to catch the Great Migration in the Serengeti alongside game drives in Tarangire, Lake Manyara and Ngorongoro. It's a private, customizable itinerary with luxury lodge and camp stays, aimed at wildlife enthusiasts, photographers and families. Best visited June to September, with an optional hot air balloon safari.",
    included: ["Great Migration viewing", "luxury lodge/camp stays", "full board meals", "park & conservation fees", "birdwatching", "optional hot air balloon safari"],
    excluded: [], whatToExpect: [], activities: [], itinerary: [], faqs: [],
    rating: { score: 0, count: 0 },
    gallery: ["/img/real-api/tours/migration-wilderness-wanderlust/1.webp"],
  },
  {
    slug: "lengais-legacy",
    title: "Lengai's Legacy",
    meta: "6 Days · Tanzania",
    img: "/img/real-api/tours/lengais-legacy/1.webp",
    days: 6, style: "Safari & Wildlife", region: "Lake Natron",
    summary: "A Rift Valley adventure combining Maasai cultural immersion at Africa Amini Maasai Lodge, exploration of the surreal Lake Natron landscape, a climb up the active volcano Ol Doinyo Lengai, and Big Five game drives in the Serengeti. It runs by private guide and 4x4, best from June to September. Optional add-ons include a hot air balloon safari, walking safari and horse riding.",
    included: ["Maasai cultural performances", "Lake Natron landscapes", "Ol Doinyo Lengai summit", "Serengeti Big Five game drives", "full board accommodation", "4x4 transport"],
    excluded: [], whatToExpect: [], activities: [], itinerary: [], faqs: [],
    rating: { score: 0, count: 0 },
    gallery: ["/img/real-api/tours/lengais-legacy/1.webp"],
  },
  {
    slug: "usambara-wonders-from-peaks-to-waterfalls",
    title: "Usambara Wonders - From Peaks to Waterfalls",
    meta: "4 Days · Tanzania",
    img: "/img/real-api/tours/usambara-wonders-from-peaks-to-waterfalls/1.webp",
    days: 4, style: "Sightseeing & Tours", region: "Lushoto (Usambara)",
    summary: "A nature-and-culture trip through the Usambara Mountains based in Lushoto, with a sunset stop at Irente Viewpoint, a guided hike through Magamba Forest Reserve, a visit to the Kisasa Waterfalls, and a tour of the sustainable Irente Farm. It's a moderate-difficulty, family-friendly itinerary run June through October. Lodging is at Irente View and Irente Farm Lodge with full board.",
    included: ["Irente Viewpoint sunset", "Magamba Forest hike", "Kisasa Waterfalls", "Irente Farm tour", "full board lodging", "stargazing at the lodge"],
    excluded: [], whatToExpect: [], activities: [], itinerary: [], faqs: [],
    rating: { score: 0, count: 0 },
    gallery: ["/img/real-api/tours/usambara-wonders-from-peaks-to-waterfalls/1.webp"],
  },
  {
    slug: "the-safari-oasis",
    title: "The Safari Oasis",
    meta: "3 Days · Tanzania",
    img: "/img/real-api/tours/the-safari-oasis/1.webp",
    days: 3, style: "Safari & Wildlife", region: "Mkomazi National Park",
    collections: ["halal"],
    summary: "A short getaway pairing relaxed tented time at Lake Chala, with a private chef preparing meals, and active game viewing at Mkomazi National Park including a rhino sanctuary visit. Day and night game drives, canoeing, hiking and walking safaris are all on offer, with private transfers between the two locations. Best suited to couples, families, birders and photographers, June to September.",
    included: ["Private chef & tented stay at Lake Chala", "lodge stay at Mkomazi", "day/night game drives", "rhino sanctuary visit", "canoeing & walking safaris", "private vehicle & guide"],
    excluded: [], whatToExpect: [], activities: [], itinerary: [], faqs: [],
    rating: { score: 0, count: 0 },
    gallery: ["/img/real-api/tours/the-safari-oasis/1.webp"],
  },
  {
    slug: "grand-tanzanian-journey",
    title: "Grand Tanzanian Journey",
    meta: "10 Days · Tanzania",
    img: "/img/real-api/tours/grand-tanzanian-journey/1.webp",
    days: 10, style: "Safari & Wildlife", region: "Serengeti National Park",
    collections: ["halal"],
    summary: "A combined safari-and-beach itinerary that strings together Tarangire, Lake Manyara's tree-climbing lions, the Ngorongoro Crater, Great Migration viewing in the Serengeti, and finishes with Stone Town and beach time in Zanzibar. It's a private, tailorable trip covering game drives, cultural tours and water sports. An optional hot air balloon safari can be added over the Serengeti.",
    included: ["Full board lodges/camps", "professional safari guide", "park entry fees", "Big Five in Ngorongoro", "Great Migration viewing", "Stone Town & beach time"],
    excluded: [], whatToExpect: [], activities: [], itinerary: [], faqs: [],
    rating: { score: 0, count: 0 },
    gallery: ["/img/real-api/tours/grand-tanzanian-journey/1.webp"],
  },
  {
    slug: "shira-discovery",
    title: "Shira Discovery",
    meta: "2 Days · Tanzania",
    img: "/img/real-api/tours/shira-discovery/1.jpg",
    days: 2, style: "Adrenaline & Adventure", region: "Mount Kilimanjaro",
    collections: ["halal"],
    summary: "A short, two-day taste of Kilimanjaro trekking that climbs through montane forest and moorland to camp overnight at Shira 1, with an optional acclimatization walk up to Shira 2. It's pitched at adventure seekers and nature lovers who are short on time rather than aiming for the summit. Guides, porters, camping gear and a trekking chef are included.",
    included: ["Guides & porters", "camping equipment", "full board meals with trekking chef", "park fees", "first aid & evacuation insurance"],
    excluded: [], whatToExpect: [], activities: [], itinerary: [], faqs: [],
    rating: { score: 0, count: 0 },
    gallery: ["/img/real-api/tours/shira-discovery/1.jpg"],
  },
  {
    slug: "jungle-escape",
    title: "Jungle Escape",
    meta: "4 Days · Tanzania",
    img: "/img/real-api/tours/jungle-escape/1.webp",
    days: 4, style: "Safari & Wildlife", region: "Tanzania",
    collections: ["halal"],
    summary: "A remote wilderness trip to Mahale National Park on Lake Tanganyika, centered on tracking wild chimpanzees with experienced guides. It's rounded out with lake activities - boat trips, snorkeling and kayaking - and stays at lodges along the shore. Best visited June to September, with a domestic flight connection from Arusha via Dar es Salaam.",
    included: ["Chimpanzee trekking permits & guides", "lodge accommodation", "boat excursions", "snorkeling/kayaking", "park & conservation fees", "domestic flight"],
    excluded: [], whatToExpect: [], activities: [], itinerary: [], faqs: [],
    rating: { score: 0, count: 0 },
    gallery: ["/img/real-api/tours/jungle-escape/1.webp"],
  },
  {
    slug: "peak-perfection",
    title: "Peak Perfection",
    meta: "6 Days · Tanzania",
    img: "/img/real-api/tours/peak-perfection/1.webp",
    days: 6, style: "Adrenaline & Adventure", region: "Arusha",
    summary: "A challenging Mount Meru climb to Socialist Peak (4,566m) that opens with a game drive through Arusha National Park before crossing montane forest, moorland and alpine terrain. It includes a Little Meru acclimatization hike and a midnight summit push with views of Kilimanjaro. Aimed at fit trekkers with some prior experience, running June through February.",
    included: ["Airport transfers & mountain hut stays", "full board meals", "guides, porters & safety gear", "park & camping fees", "game drive", "first aid & emergency oxygen"],
    excluded: [], whatToExpect: [], activities: [], itinerary: [], faqs: [],
    rating: { score: 0, count: 0 },
    gallery: ["/img/real-api/tours/peak-perfection/1.webp"],
  },
  {
    slug: "virunga-vistas",
    title: "Virunga Vistas",
    meta: "5 Days · Tanzania",
    img: "/img/real-api/tours/virunga-vistas/1.webp",
    days: 5, style: "Safari & Wildlife", region: "Tanzania",
    summary: "A Rwanda gorilla-trekking trip based around Volcanoes National Park, with options to add golden monkey trekking or a Dian Fossey hike, plus a cultural village visit. Trek length to reach a gorilla family runs one to four hours each way, and the minimum age is 15. Guides, trackers, permits, park fees and lodge stays with full board are included.",
    included: ["Gorilla & golden monkey trekking permits", "professional guides/trackers", "full board lodge stays", "cultural village visit", "private 4x4 transport"],
    excluded: [], whatToExpect: [], activities: [], itinerary: [], faqs: [],
    rating: { score: 0, count: 0 },
    gallery: ["/img/real-api/tours/virunga-vistas/1.webp"],
  },
  {
    slug: "natures-harmony",
    title: "Nature's Harmony",
    meta: "6 Days · Tanzania",
    img: "/img/real-api/tours/natures-harmony/1.webp",
    days: 6, style: "Safari & Wildlife", region: "Tanzania",
    collections: ["halal"],
    summary: "A southern Tanzania trip that pairs open-plains game drives in Mikumi with a hike to the Sanje Waterfalls and a walk through Magombera forest in the Udzungwa Mountains. It's a private, customizable itinerary at a moderate activity level, with lodge/camp stays and all park fees included. Best done in the dry seasons, June-October or January-February.",
    included: ["Full-day Mikumi game drives", "Sanje Waterfall hike", "Magombera forest walk", "birdwatching", "lodge/camp accommodation", "airport transfers from Dar es Salaam"],
    excluded: [], whatToExpect: [], activities: [], itinerary: [], faqs: [],
    rating: { score: 0, count: 0 },
    gallery: ["/img/real-api/tours/natures-harmony/1.webp"],
  },
  {
    slug: "mara-moments",
    title: "Mara Moments",
    meta: "6 Days · Tanzania",
    img: "/img/real-api/tours/mara-moments/1.webp",
    price: 2500,
    days: 6, style: "Safari & Wildlife", region: "Tanzania",
    collections: ["halal"],
    summary: "A private Kenyan safari that moves from Nairobi (with a stop at the Sheldrick Elephant Orphanage and Giraffe Centre) to Lake Nakuru and on to the Maasai Mara for Big Five game drives. Local guides run the trip in a private 4x4, with full board lodges and an optional sunrise hot air balloon safari. International flights, visas and insurance are excluded.",
    included: ["Private 4x4 & guide", "full board lodges", "park entry fees", "Big Five game drives", "optional hot air balloon safari", "cultural market visit"],
    excluded: [], whatToExpect: [], activities: [], itinerary: [], faqs: [],
    rating: { score: 0, count: 0 },
    gallery: ["/img/real-api/tours/mara-moments/1.webp", "/img/real-api/tours/mara-moments/2.jpg"],
  },
  {
    slug: "teaching-awareness-volunteering",
    title: "Teaching & Awareness Volunteering",
    meta: "14 Days · Tanzania",
    img: "/img/real-api/tours/teaching-awareness-volunteering/1.webp",
    price: 7600,
    days: 14, style: "Cultural & Community", region: "Mount Kilimanjaro",
    summary: "A two-week teaching placement run in partnership with Neema International, supporting orphaned and vulnerable children through academic, emotional and social development work alongside local teachers and caregivers. Volunteers teach math, English and science and take part in mentorship and confidence-building activities. Basic Swahili lessons and optional excursions to Ngorongoro, Tarangire and Arusha are included.",
    included: ["Accommodation & full board", "airport transfers", "project materials", "basic Swahili lessons", "one-on-one mentorship", "optional day excursions"],
    excluded: [], whatToExpect: [], activities: [], itinerary: [], faqs: [],
    rating: { score: 0, count: 0 },
    gallery: ["/img/real-api/tours/teaching-awareness-volunteering/1.webp"],
  },
  {
    slug: "clinical-health-provider-volunteering-in-tanzania",
    title: "Clinical Health Provider Volunteering in Tanzania",
    meta: "5 Days · Tanzania",
    img: "/img/real-api/tours/clinical-health-provider-volunteering-in-tanzania/1.webp",
    days: 5, style: "Cultural & Community", region: "Mount Kilimanjaro",
    summary: "A clinical placement for medical students and healthcare professionals working under supervision in Kilimanjaro-area hospitals, addressing local health challenges such as malaria, HIV/AIDS and maternal-child health. Volunteers assist with patient consultations, assessments and community health education. Run by a family operator active since 1983, with an optional safari extension on the final day.",
    included: ["Hospital placements with mentorship", "orientation & healthcare system training", "patient consultation assistance", "community health campaigns", "optional safari extension"],
    excluded: [], whatToExpect: [], activities: [], itinerary: [], faqs: [],
    rating: { score: 0, count: 0 },
    gallery: ["/img/real-api/tours/clinical-health-provider-volunteering-in-tanzania/1.webp"],
  },
  {
    slug: "public-health-trainer",
    title: "Public Health Trainer",
    meta: "5 Days · Tanzania",
    img: "/img/real-api/tours/public-health-trainer/1.webp",
    days: 5, style: "Cultural & Community", region: "Mount Kilimanjaro",
    summary: "A community health volunteering placement where participants run workshops on hygiene, sanitation, disease prevention and nutrition alongside local health workers and schools. It suits health students, educators and anyone wanting hands-on public health experience. Accommodation, meals, transfers and volunteering facilities are covered; visas, insurance and flights are not.",
    included: ["Public health workshops", "community hygiene & nutrition programs", "school outreach", "accommodation & meals", "airport transfers", "optional cultural activities"],
    excluded: [], whatToExpect: [], activities: [], itinerary: [], faqs: [],
    rating: { score: 0, count: 0 },
    gallery: ["/img/real-api/tours/public-health-trainer/1.webp"],
  },
  {
    slug: "marangu-route-8-day-adventure-to-the-kilimanjaro-summit",
    title: "Marangu Route - 8 Day Adventure to the Kilimanjaro Summit",
    meta: "8 Days · Tanzania",
    img: "/img/real-api/tours/marangu-route-8-day-adventure-to-the-kilimanjaro-summit/1.jpg",
    days: 8, style: "Adrenaline & Adventure", region: "Mount Kilimanjaro",
    summary: "The only Kilimanjaro route with sleeping huts rather than tents, making it a popular choice for trekkers who want a bit more comfort on the mountain. Daily distances range from 8 to 20km through rainforest, heathland and alpine terrain, with a rest day at Horombo Hut to aid acclimatization before the summit push. Moshi hotel stays bookend the trek.",
    included: ["Hut accommodation", "guides", "park/hut & rescue fees", "acclimatization day at Horombo", "all meals", "summit certificate"],
    excluded: [], whatToExpect: [], activities: [], itinerary: [], faqs: [],
    rating: { score: 0, count: 0 },
    gallery: ["/img/real-api/tours/marangu-route-8-day-adventure-to-the-kilimanjaro-summit/1.jpg"],
  },
  {
    slug: "ndutu-migration-safari",
    title: "Ndutu Migration Safari",
    meta: "6 Days · Tanzania",
    img: "/img/real-api/tours/ndutu-migration-safari/1.webp",
    price: 2600,
    days: 6, style: "Safari & Wildlife", region: "Serengeti National Park",
    collections: ["halal"],
    summary: "A driving safari built around the wildebeest calving season, with a full day in Tarangire, three nights based in Ndutu for migration and calving action, and a full day exploring the Ngorongoro Crater's Big Five. Travel is by private 4x4 with pop-up roof and an English-speaking guide, and the pace suits all fitness levels since walking is minimal. Best visited January through March.",
    included: ["Private 4x4 with pop-up roof", "full board lodges/camps", "park entry fees", "picnic lunches", "optional hot air balloon safari & Maasai village visit"],
    excluded: [], whatToExpect: [], activities: [], itinerary: [], faqs: [],
    rating: { score: 0, count: 0 },
    gallery: ["/img/real-api/tours/ndutu-migration-safari/1.webp"],
  },
  {
    slug: "machame-route-8-day-adventure-to-conquer-kilimanjaro",
    title: "Machame Route - 8-Day Adventure to Conquer Kilimanjaro",
    meta: "8 Days · Tanzania",
    img: "/img/real-api/tours/machame-route-8-day-adventure-to-conquer-kilimanjaro/1.webp",
    days: 8, style: "Adrenaline & Adventure", region: "Mount Kilimanjaro",
    summary: "Known as the 'Whiskey' route, this is one of Kilimanjaro's more scenic and popular paths, crossing rainforest, moorland and alpine terrain before a midnight summit push to Uhuru Peak. It calls for moderate-to-high fitness and mixes two Moshi hotel nights with tent camping on the mountain. Guides, meals, park fees and safety gear are included throughout.",
    included: ["Airport transfers & Moshi hotel nights", "all trek meals", "guides", "park/hut & rescue fees", "portable oxygen", "summit certificate"],
    excluded: [], whatToExpect: [], activities: [], itinerary: [], faqs: [],
    rating: { score: 0, count: 0 },
    gallery: ["/img/real-api/tours/machame-route-8-day-adventure-to-conquer-kilimanjaro/1.webp"],
  },
  {
    slug: "lemosho-route-10-day-adventure-to-the-summit-of-mt-kilimanjaro",
    title: "Lemosho Route - 10 Day Adventure to the Summit of Mt. Kilimanjaro",
    meta: "10 Days · Tanzania",
    img: "/img/real-api/tours/lemosho-route-10-day-adventure-to-the-summit-of-mt-kilimanjaro/1.webp",
    days: 10, style: "Adrenaline & Adventure", region: "Mount Kilimanjaro",
    summary: "A longer, gentler Kilimanjaro route starting at Londorossi Gate that crosses rainforest, alpine desert and near-arctic terrain on the way to Uhuru Peak (5,895m). The extra days build in better acclimatization, which tends to raise summit success rates for moderately fit trekkers. Moshi hotel nights, tent camping, guides and a summit certificate are included.",
    included: ["Guides & mountain crew", "Moshi hotel stays before/after", "all trek meals", "park/hut/rescue fees", "portable oxygen", "summit certificate"],
    excluded: [], whatToExpect: [], activities: [], itinerary: [], faqs: [],
    rating: { score: 0, count: 0 },
    gallery: ["/img/real-api/tours/lemosho-route-10-day-adventure-to-the-summit-of-mt-kilimanjaro/1.webp"],
  },
  {
    slug: "umbwe-route-6-day-challenge-to-the-summit-of-mt-kilimanjaro",
    title: "Umbwe Route - 6-Day Challenge to the Summit of Mt. Kilimanjaro",
    meta: "6 Days · Tanzania",
    img: "/img/real-api/tours/umbwe-route-6-day-challenge-to-the-summit-of-mt-kilimanjaro/1.webp",
    days: 6, style: "Adrenaline & Adventure", region: "Mount Kilimanjaro",
    summary: "The steepest and least-traveled of Kilimanjaro's standard routes, climbing quickly through rainforest, moorland and alpine desert with minimal crowds. Its rapid ascent profile raises altitude-sickness risk, so it's recommended for fit, experienced trekkers only, with a midnight summit push on the final day. Moshi hotel stays bracket the climb.",
    included: ["English-speaking guides", "Moshi hotel stays", "all trek meals", "park & rescue fees", "portable oxygen & first aid kit", "sunrise summit at Uhuru Peak"],
    excluded: [], whatToExpect: [], activities: [], itinerary: [], faqs: [],
    rating: { score: 0, count: 0 },
    gallery: ["/img/real-api/tours/umbwe-route-6-day-challenge-to-the-summit-of-mt-kilimanjaro/1.webp"],
  },
  {
    slug: "tree-nursery-development-management",
    title: "Tree Nursery Development & Management",
    meta: "11 Days · Tanzania",
    img: "/img/real-api/tours/tree-nursery-development-management/1.webp",
    price: 7200,
    days: 11, style: "Cultural & Community", region: "Mount Kilimanjaro",
    summary: "A hands-on forest-restoration placement at a tree nursery near Moshi, covering the full propagation cycle for native and fruit species: soil prep, seed sorting, potting, planting and ongoing care. No prior experience is needed, and the seedlings raised go toward restoring degraded land in the region. Community education sessions and optional national park day trips round out the stay.",
    included: ["Nursery management & soil prep training", "native/fruit tree propagation", "natural pest control practices", "community awareness sessions", "certificate of participation", "optional park day trips"],
    excluded: [], whatToExpect: [], activities: [], itinerary: [], faqs: [],
    rating: { score: 0, count: 0 },
    gallery: ["/img/real-api/tours/tree-nursery-development-management/1.webp"],
  },
  {
    slug: "rongai-route-kilimanjaro-trek",
    title: "Rongai Route Kilimanjaro Trek",
    meta: "7 Days · Tanzania",
    img: "/img/real-api/tours/rongai-route-kilimanjaro-trek/1.webp",
    days: 7, style: "Adrenaline & Adventure", region: "Mount Kilimanjaro",
    summary: "A moderate, gradual ascent of Kilimanjaro from the quieter Rongai Gate, valued for its remoteness and comparatively high summit success rate. The route offers views of both Kibo and Mawenzi peaks before reaching Uhuru Peak (5,895m) at sunrise. Two Moshi hotel nights, tent camps on the mountain, guides and rescue cover are included.",
    included: ["Hotel nights in Moshi", "tent camps", "professional guides", "park/hut & rescue fees", "portable oxygen", "sunrise summit", "fair crew wages"],
    excluded: [], whatToExpect: [], activities: [], itinerary: [], faqs: [],
    rating: { score: 0, count: 0 },
    gallery: ["/img/real-api/tours/rongai-route-kilimanjaro-trek/1.webp"],
  },
  {
    slug: "shira-route-kilimanjaro-trek",
    title: "Shira Route Kilimanjaro Trek",
    meta: "7 Days · Tanzania",
    img: "/img/real-api/tours/shira-route-kilimanjaro-trek/1.webp",
    price: 2000,
    days: 7, style: "Adrenaline & Adventure", region: "Mount Kilimanjaro",
    summary: "A less-crowded western approach to Kilimanjaro that starts at higher elevation and crosses the Shira Plateau's moorland and alpine desert on the way to Uhuru Peak (5,895m). Best suited to experienced hikers, it follows a 'climb high, sleep low' acclimatization plan and reports a roughly 85-90% summit success rate on the 7-day version. Two Moshi hotel nights bookend the trek.",
    included: ["English-speaking guides", "all trek meals", "tent camps", "park & hut fees", "portable oxygen & first aid", "airport transfers", "rescue fees"],
    excluded: [], whatToExpect: [], activities: [], itinerary: [], faqs: [],
    rating: { score: 0, count: 0 },
    gallery: ["/img/real-api/tours/shira-route-kilimanjaro-trek/1.webp", "/img/real-api/tours/shira-route-kilimanjaro-trek/2.webp", "/img/real-api/tours/shira-route-kilimanjaro-trek/3.jpg", "/img/real-api/tours/shira-route-kilimanjaro-trek/4.jpg", "/img/real-api/tours/shira-route-kilimanjaro-trek/5.jpg"],
  },
  {
    slug: "wild-ecology-conservation-program",
    title: "Wild Ecology Conservation Program",
    meta: "12 Days · Tanzania",
    img: "/img/real-api/tours/wild-ecology-conservation-program/1.webp",
    price: 7200,
    days: 12, style: "Cultural & Community", region: "Arusha",
    summary: "A conservation volunteering program covering wildlife monitoring, habitat restoration and climate-change field research around Kilimanjaro's ecosystems, working alongside rangers and conservation professionals. Open to adults 18+ with no prior experience needed, it includes tree planting, biodiversity surveys and data analysis. Optional day trips to Ngorongoro, Tarangire or Arusha National Park round out the program.",
    included: ["Accommodation & daily meals", "airport transfers", "wildlife monitoring", "habitat restoration & tree planting", "environmental education workshops", "certificate of participation"],
    excluded: [], whatToExpect: [], activities: [], itinerary: [], faqs: [],
    rating: { score: 0, count: 0 },
    gallery: ["/img/real-api/tours/wild-ecology-conservation-program/1.webp"],
  },
  {
    slug: "4-days-mount-meru",
    title: "4 Days Mount Meru",
    meta: "4 Days · Tanzania",
    img: "/img/real-api/tours/4-days-mount-meru/1.jpg",
    days: 4, style: "Adrenaline & Adventure", region: "Arusha",
    summary: "A slightly longer, more gradual ascent of Mount Meru than the 3-day option, giving extra time for forest walks and wildlife viewing in Arusha National Park before the midnight summit push. Trekkers pass through montane forest and moorland zones and are rewarded with sunrise views over Kilimanjaro and the surrounding plains. Meals, huts, guides and airport transfers are included.",
    included: ["Guided summit trek", "scenic forest walks", "wildlife encounters", "airport transfers", "all meals", "park entrance fees", "cultural interactions"],
    excluded: [], whatToExpect: [], activities: [], itinerary: [], faqs: [],
    rating: { score: 0, count: 0 },
    gallery: ["/img/real-api/tours/4-days-mount-meru/1.jpg"],
  },
  {
    slug: "3-days-mount-meru",
    title: "3 Days Mount Meru",
    meta: "3 Days · Tanzania",
    img: "/img/real-api/tours/3-days-mount-meru/1.jpg",
    days: 3, style: "Adrenaline & Adventure", region: "Arusha",
    collections: ["halal"],
    summary: "A short trek up Mount Meru's Socialist Peak (4,562m) through forest and moorland inside Arusha National Park, with an armed ranger along for wildlife safety since the lower slopes hold buffalo and other game. Open to trekkers aged 12 and up in good fitness, with a midnight summit push for sunrise views of Kilimanjaro. Huts, all meals and airport transfers are included.",
    included: ["Mountain hut & hotel stays", "all meals", "guides & armed ranger", "park & conservation fees", "midnight summit attempt", "summit certificate"],
    excluded: [], whatToExpect: [], activities: [], itinerary: [], faqs: [],
    rating: { score: 0, count: 0 },
    gallery: ["/img/real-api/tours/3-days-mount-meru/1.jpg"],
  },
  {
    slug: "rescue-kilimanjaro-snow",
    title: "Rescue Kilimanjaro Snow",
    meta: "12 Days · Tanzania",
    img: "/img/real-api/tours/rescue-kilimanjaro-snow/1.webp",
    price: 7200,
    days: 12, style: "Cultural & Community", region: "Mount Kilimanjaro",
    summary: "A climate-focused volunteering program built around Kilimanjaro's retreating glaciers, combining tree planting in deforested zones with basic climate field research and community education. It targets environmentally minded travelers, students and climate activists, with medical staff and guides on hand throughout. Optional safari add-ons to Ngorongoro, Tarangire and Arusha National Park are available.",
    included: ["Accommodation & daily meals", "airport transfers", "tree planting & ecosystem restoration", "climate research and data work", "community campaigns", "certificate of participation"],
    excluded: [], whatToExpect: [], activities: [], itinerary: [], faqs: [],
    rating: { score: 0, count: 0 },
    gallery: ["/img/real-api/tours/rescue-kilimanjaro-snow/1.webp"],
  },
  {
    slug: "ndutu-life-awakens",
    title: "Ndutu Life Awakens",
    meta: "8 Days · Tanzania",
    img: "/img/real-api/tours/ndutu-life-awakens/1.webp",
    price: 3200,
    days: 8, style: "Safari & Wildlife", region: "Serengeti National Park",
    collections: ["halal"],
    summary: "A safari timed to the wildebeest calving season, when hundreds of thousands of calves are born on the Ndutu plains between late January and early March. The trip pairs this predator-and-prey spectacle with Big Five game viewing in the Ngorongoro Crater, traveling by private 4x4 with a pop-up roof. All lodging, meals, park fees and guiding are included.",
    included: ["Private 4x4 with pop-up roof", "English-speaking driver-guide", "full board lodges/camps", "park & conservation fees", "airport transfers", "optional birdwatching, sundowners & cultural visits"],
    excluded: [], whatToExpect: [], activities: [], itinerary: [], faqs: [],
    rating: { score: 0, count: 0 },
    gallery: ["/img/real-api/tours/ndutu-life-awakens/1.webp"],
  },
  {
    slug: "cycling-and-tree-planting-volunteering-program",
    title: "Cycling and Tree Planting Volunteering Program",
    meta: "6 Days · Tanzania",
    img: "/img/real-api/tours/cycling-and-tree-planting-volunteering-program/1.webp",
    price: 550,
    days: 6, style: "Cultural & Community", region: "Arusha",
    summary: "An eco-volunteering program that pairs cycling with hands-on native tree planting to help restore local ecosystems around Kilimanjaro and Arusha. Volunteers bike out to planting sites and take part in community environmental education. Open to all fitness levels and available for stays of a week or longer.",
    included: ["Accommodation & meals", "airport transfers (1+ week stays)", "transport to planting sites", "community engagement activities", "certificate of participation", "optional cultural excursions"],
    excluded: [], whatToExpect: [], activities: [], itinerary: [], faqs: [],
    rating: { score: 0, count: 0 },
    gallery: ["/img/real-api/tours/cycling-and-tree-planting-volunteering-program/1.webp"],
  },
  {
    slug: "arts-and-sports-volunteering-in-tanzania",
    title: "Arts and Sports Volunteering in Tanzania",
    meta: "6 Days · Tanzania",
    img: "/img/real-api/tours/arts-and-sports-volunteering-in-tanzania/1.webp",
    price: 7350,
    days: 6, style: "Cultural & Community", region: "Arusha",
    summary: "A volunteer placement in Arusha where participants coach football, netball, athletics and fitness at local schools and youth clubs. Aimed at students, gap-year travelers and educators, no coaching background is required. Runs from one to twelve weeks and can be combined with safari add-ons and cultural visits.",
    included: ["Accommodation & daily breakfast/dinner", "airport transfers", "volunteer coordinator", "sports equipment provided", "completion certificate", "optional Maasai village & market visits"],
    excluded: [], whatToExpect: [], activities: [], itinerary: [], faqs: [],
    rating: { score: 0, count: 0 },
    gallery: ["/img/real-api/tours/arts-and-sports-volunteering-in-tanzania/1.webp"],
  },
];

export function getTour(slug: string) {
  return TOURS.find((t) => t.slug === slug);
}